#!/usr/bin/bash

#: Title       : System 3
#: Date        : Oct 20 2022
#: Author      : Andrew Hull
#: Version     : 1.0
#: Description : Backup a dir
#: Options     : to name the backup file, if no name is provided use a default that includes the date.
#reference https://www.youtube.com/watch?v=MCx5p8acsE0
#backup a directory or directories to a specific location.

#Have a default location as well as the ability to pass a location as an argument: cp

#create an archived file `.tar.gz` from your directory or list of directories: tar

#have an option to name the backup file, if no name is provided use a default that includes the date: mv


LOCATION = $(dirname "$0")

function check_directory {
	echo "checking directory"
	if [! -s "/backup_dir.conf"]
	then
		echo "Create list of dir"
		exit 1
	fi
}

function backup_location {
	echo "checking backup location"
	if [! -s "/backup_location.conf"]
        then
                echo "Create list of dir"
                exit 1
        fi
}


function backup {
	path=$(cat /backup_location.conf)
	echo "making backup" > $LOCATION
	
	while read dir_path
	do
		dir_name=$(basename $dir_path)
		
		filename=$path$dir_name.tar.xz

		tar -zcf $filename $path 2>> $LOCATION

		chown captain:captain $filename

		echo "backing up the file" >> $LOCATION
	
	done < /backup_dirs.conf
	
	echo "Completed at" >> $LOCATION
	date >> $LOCATION
}
check_directory
backup_location
backup

