#!/usr/bin/bash
 #: Title
#: Date
#: Author
#: Version
#: Description : write short notes, read notes, search for notes by tags, title or date #: Options : (tags, title or date)
: Quick note taking CLI : Oct 20 2022
: Andrew Hull : 1.0
Quick note taking CLI

write short notes

read notes

search for notes by tags, title or date.

auto append a date to a note when the note is created.
Notes should have a title.
Notes should have optional tags.

Your notes will be stored as plain text (ie not in a database)

use options for selecting search(tags, title or date)

Things to consider: How will notes be organized? Single file, or multiple directories of notes.

Don’t just use Vim(or another text editor) to write notes. You are creating a script that will write text to a file.
hint, you probably don’t want to use read for the actual note.
write_file() {

	read -p "Create file" FILE
	while [ -f ${NOTES_DIR}/${FILE} ]; do
		echo "${FILE} already exist, select a new name)"
		read -p "Create new file" FILE
	done
}
function writeInFile 0){
